apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: users
spec:
  host: users
  trafficPolicy:
    tls:
      mode: DISABLE
      
  subsets:
    - name: prod
      labels:
        scope: prod