apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-prod
  annotations:
    sidecar.istio.io/statsInclusionPrefixes: "cluster.outbound|80||items.core-services.svc.cluster.local"
  labels:
    app: users
    scope: prod
    version: v6
spec:
  selector:
    matchLabels:
      app: users
      scope: prod
  template:
    metadata:
      annotations:
        sidecar.istio.io/statsInclusionPrefixes: "cluster.outbound|80||items.core-services.svc.cluster.local"
      labels:
        app: users
        scope: prod
        version: v6
    spec:
      containers:
        - name: users
          image: clazz/users-svc:6
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8089
              protocol: TCP
              name: http
          env:
            - name: ITEMS_URL
              value: http://items/items
    